project:
  type: book
  resources:
    - js/
    - assets/

execute:
  freeze: auto

book:
  title: "Epidemic Preparedness and Response"
  author:
    - name: Thinh Ong
      url: https://drthinhong.com/
      orcid: 0000-0001-6772-9291
  date: "26/06/2026"
  site-url: https://thinhong.github.io/epr/
  repo-url: https://github.com/thinhong/epr
  chapters:
    - index.qmd
    - part: epithreshold.qmd
      chapters:
        - cusum.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - assets/theme.scss
    include-in-header: assets/head-fonts.html
    css: assets/tokens.css
